## Consider the below code to answer further questions:


In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
### Ans:
Yes, data type of variables list_ and array_list are different. 
1. list_ : it is a list data type
2. array_list: it is a array data type with dimention 1

In [2]:
list_

['1', '2', '3', '4', '5']

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

In [6]:
array_list.ndim

1

*************************************************************************************************************************************

## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [7]:
for element in list_:
    print(element, type(element))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [8]:
for element in array_list:
    print(element, type(element))

1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


*************************************************************************************************************************************

## Q3. Considering the following changes in the variable, array_list:

In [9]:
array_list = np.array(object = list_, dtype = int)

### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list?

### Ans:
Yes, data type of variables list_ and array_list are different. 
1. list_ : it is a list data type
2. array_list: it is a array data type with dimention 1

In [10]:
type(list_)

list

In [11]:
type(array_list)

numpy.ndarray

### If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [12]:
for element in list_:
    print(element, type(element))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [13]:
for element in array_list:
    print(element, type(element))

1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


*************************************************************************************************************************************

## Consider the below code to answer further questions:

In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## Q4. Write a code to find the following characteristics of variable, num_array:


### (i) shape

In [15]:
num_array.shape

(2, 3)

### (ii) size

In [16]:
np.size(num_array)

6

*************************************************************************************************************************************

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#### [Hint: The size of the array will be 9 and the shape will be (3,3).]

### Ans:

In [17]:
zero_matrix = np.zeros((3,3))

In [18]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?
#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

### Ans:

### Approach with array type

In [19]:
identity_matrix1 = np.eye(5)
identity_matrix1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
identity_matrix1.shape

(5, 5)

In [21]:
type(identity_matrix1)

numpy.ndarray

### Approach with matrix type

In [22]:
import numpy.matlib as nm
identity_matrix2 = nm.eye(5)
identity_matrix2

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [23]:
identity_matrix2.shape

(5, 5)

In [24]:
type(identity_matrix2)

numpy.matrix